
import {
    Home,
    BookOpenCheck,
    CheckSquare,
    Newspaper,
    User,
    ShieldCheck,
    ClipboardPen,
    Briefcase,
    RadioTower,
    GraduationCap,
    MessageSquare,
    ScrollText,
    Scissors,
    Trophy,
    CircleDot,
    Video,
    Download,
    Users,
    List,
    Phone,
    Cog,
    BookCopy,
    Library,
    MessagesSquare,
    Youtube
  } from 'lucide-react';
  
  export const featureGridLinks = [
      { href: "/group-chat", icon: MessagesSquare, textKey: "groupChat" },
      { href: "/student-portal", icon: Briefcase, textKey: "studentPortal" },
      { href: "/courses", icon: BookOpenCheck, textKey: "ourCourses" },
      { href: "/live-classes", icon: RadioTower, textKey: "liveClasses" },
      { href: "/daily-posts", icon: Newspaper, textKey: "dailyPosts" },
      { href: "/tests", icon: CheckSquare, textKey: "aiTest" },
      { href: "/ai-tutor", icon: GraduationCap, textKey: "aiTutor" },
      { href: "/cutoff-checker", icon: Scissors, textKey: "cutoffChecker" },
      { href: "/youtube", icon: BookCopy, textKey: "gdaLearning" },
  ];
  
  export const sidebarLinks = [
    { href: "/home", icon: Home, textKey: "dashboard" },
    { href: "/courses", icon: BookOpenCheck, textKey: "ourCourses" },
    { href: "/scholarship", icon: ClipboardPen, textKey: "scholarshipForm" },
    { href: "/student-portal", icon: Briefcase, textKey: "studentPortal" },
    { href: "/live-classes", icon: RadioTower, textKey: "liveClasses" },
    { href: "/video-lectures", icon: Video, textKey: "videoLectures" },
    { href: "/youtube", icon: BookCopy, textKey: "gdaLearning" },
    { href: "/downloads", icon: Download, textKey: "downloads" },
    { href: "/e-books", icon: Library, textKey: "ebooks" },
    { href: "/tests", icon: CheckSquare, textKey: "aiTest" },
    { href: "/ai-tutor", icon: GraduationCap, textKey: "aiTutor" },
    { href: "/group-chat", icon: MessagesSquare, textKey: "groupChat" },
    { href: "/current-affairs", icon: ScrollText, textKey: "currentAffairs" },
    { href: "/cutoff-checker", icon: Scissors, textKey: "cutoffChecker" },
    { href: "/toppers", icon: Trophy, textKey: "toppers" },
    { href: "/teachers", icon: Users, textKey: "teachers" },
    { href: "/school-list", icon: List, textKey: "schoolList" },
    { href: "/contact", icon: Phone, textKey: "contact" },
    { href: "/admin", icon: Cog, textKey: "adminPanel" },
  ];

  export const bottomNavLinks = [
      { textKey: 'navHome', href: '/home', icon: Home },
      { textKey: 'navCourses', href: '/courses', icon: BookOpenCheck },
      { textKey: 'navTest', href: '/tests', icon: CheckSquare },
      { textKey: 'navPosts', href: '/daily-posts', icon: Newspaper },
      { textKey: 'navAccount', href: '/account', icon: User },
  ];
